# SPDX-License-Identifier: GPL-2.0
# Makefile for seamldr and tdx module

obj-y	+= seam.o seamcall.o p-seamldr.o
obj-y	+= tdx-error.o tdx.o tdmr-common.o tdmr-sysmem.o tdx-tdmr.o
obj-$(CONFIG_ENABLE_TDX_FOR_X86_PMEM_LEGACY)	+= tdmr-legacy-pmem.o
